apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-java-app.name" . }}
  labels:
    {{- include "simple-java-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-java-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-java-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "simple-java-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "simple-java-app.name" . }}-config
            - secretRef:
                name: {{ include "simple-java-app.name" . }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
