apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-java-app.name" . }}-secret
  labels:
    {{- include "simple-java-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
